### ISSUE TITLE
4.0 Support

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/electron-app#41]
At the moment trying to run it under node >= 4.0 results in this failure:

```
Uncaught Exception:
Error: non-zero exit code 1
  while running: /Users/dignifiedquire/opensource/ipfs/electron-app/node_modules/subcomandante/subcom 4955 /Users/dignifiedquire/opensource/ipfs/electron-app/node_modules/ipfsd-ctl/node_modules/.bin/ipfs version

  events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /Users/dignifiedquire/opensource/ipfs/electron-app/node_modules/ipfsd-ctl/node_modules/.bin/ipfs ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

    at ChildProcess.<anonymous> (/Users/dignifiedquire/opensource/ipfs/electron-app/node_modules/comandante/index.js:19:27)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:996:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1069:5)
```

**Comment by Dignifiedquire** [comment]
Should be fixed as far as I can tell
